### ISSUE TITLE
Add support for file-based whitespace control

### ISSUE THREAD

**Issue by onedr0p** [kpfleming/jinjanator#39]
Hi 👋🏼 

Thanks for keeping up with this project, it's much more useful that what I was doing with envsubst. 

I have one problem though, there doesn't seem to be any support for enabling [trim_blocks or lstrip_blocks](https://jinja.palletsprojects.com/en/3.0.x/templates/#whitespace-control). Ideally I would like the output below to not include the empty new lines.

The way Ansible solves this problem is to allow them to be toggle on a per-file basis using comments like below...

## Template

```yaml
#jinja2: trim_blocks: True, lstrip_blocks: True
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync-dst-{{ APP }}
  namespace: '{{ NS }}'
spec:
  trigger:
    manual: restore-once
  restic:
    repository: '{{ APP }}-volsync-secret'
    destinationPVC: '{{ CLAIM }}'
    copyMethod: Direct
    storageClassName: '{{ CLASS_NAME }}'
    accessModes: {{ ACCESS_MODES }}
    {% if env('PREVIOUS') | default(None) %}
    previous: {{ PREVIOUS }}
    {% else %}
    restoreAsOf: '{{ RESTORE_AS_OF }}' # 2022-12-10T16:00:00-05:00
    {% endif %}
    moverSecurityContext:
      runAsUser: '{{ PUID }}'
      runAsGroup: '{{ PGID }}'
      fsGroup: '{{ PGID }}'
```

## Rendered output

```yaml
#jinja2: trim_blocks: True, lstrip_blocks: True
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync-dst-qbittorrent
  namespace: 'default'
spec:
  trigger:
    manual: restore-once
  restic:
    repository: 'qbittorrent-volsync-secret'
    destinationPVC: 'qbittorrent'
    copyMethod: Direct
    storageClassName: 'qbittorrent'
    accessModes: ["ReadWriteMany"]
    
    # Set to the last X number of snapshots to restore from
    previous: 2
    
    moverSecurityContext:
      runAsUser: '568'
      runAsGroup: '568'
      fsGroup: '568'
```
