### ISSUE TITLE
jinjanate outputs superfluous version lines on resulting template

### ISSUE THREAD

**Issue by onedr0p** [kpfleming/jinjanator#41]
Hi again,

I would expect the default behavior of templating would be the _exact_ output of the template but hydrated with the logic/vars without specifying `--quiet`.

```sh
jinjanate replicationdestination.yaml.j2
```

```yaml
jinjanate 24.3.0, Jinja2 3.1.4
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
# ...
```

Ref: https://github.com/kpfleming/jinjanator/blob/c52fa3e1907eb36615d6e6ba0219cec73b1e61af/src/jinjanator/cli.py#L286-L287

Maybe this line can go under a `--verbose` arg instead? Curious to hear your thoughts, thanks!
